---
title: "01_CMMNSummary"
author: "Danielle Ethier"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load Packages

```{r Pacakges, echo=FALSE}

install.packages("remotes")
remotes::install_github("BirdStudiesCanada/naturecounts")

library(naturecounts)
library(dplyr)
library(reshape)

```

#Output directory

Create an output directory with the name you want. Here I have chose MonthYear. . 
```{r Directory, echo=FALSE}

out.dir <- paste("./Output/", "Feb2021", "/", sep = "")
dir.create(out.dir, showWarnings=FALSE, recursive=TRUE)

```

#Analysis Parameters

Load the analysis parameters file. This will tell you the names of all the CMMN stations, start year, and end year if applicable. 

```{r Anal Param, echo=FALSE}

anal.param<-read.csv("CMMN_Summary_Parameters.csv")

#to assign a max year if none is provided
max.year<-2019

```

#Site Loop

```{r site loop, echo=FALSE}

##Download Data 
#The user will need to have a naturecounts account and will need to have requested permission to access the data through the web portal system. Because I have full access my code does not include the `request_id`.

#Here we will loop through the anal.param file and summarize the data that we want.The user can also set `t` to the sites they have permission to access. 

for(t in 1:nrow(anal.param)) { #loop through each site in the Anal.param file


# Choose site based on the row number in the anal.param file for testing
t <-6

collection <- as.character(anal.param[t, "collection"])
station <- as.character(anal.param[t, "station"])
site <- as.character(anal.param[t, "site"])

#load data from naturecounts
#filters can be set to limit the amount of data dowloaded (e.g., years=c(1995, 2019)) 

data.dl <- nc_data_dl(collections=collection, username = "dethier", info = "CMMN Data Summary Script", warn = FALSE)

##Filter 
#Here is an example of a custom filter made for a project wanting to know which CMMN stations have spring banding data (ObservationCount4)from 1995-2019. 

#ObservationCount = Daily Estimated Totals
#ObservationCount2 = Daily Standardized Totals
#ObservationCount3 = Census Count
#ObservationCount4 = Number Banded


#select the columns you want to work with
in.data<-data.dl %>%select("project_id", "ObservationCount4",  "SiteCode", "survey_year", "survey_month", "survey_day", "species_id")

#load the species_id file to be mergerd with the in.data
sp.id<-search_species_code()
in.data<-left_join(in.data, sp.id, by="species_id")

#assign doy using the naturecounts helper function
in.data <- format_dates(in.data)

#now assign season using the doy column     
in.data <- in.data %>% mutate(season = if_else(doy < 180, "Spring", "Fall"))
  
#filter data collected in the spring within the given year range. Note the years filter here is redundant since the data were filter on download
in.data <- in.data %>% 
 # filter(survey_year>=1995 & survey_year<=2019) %>% 
  filter(season == "Spring")

##Summarize
#Now we can create a summary of how many speices are banded each spring

#need to ensure the data type is correct for each column
in.data$Year<-as.factor(in.data$survey_year)
in.data$SpeciesCode<-as.factor(in.data$BSCDATA)
in.data$Band<-as.integer(in.data$ObservationCount4)

sp.dat<-in.data %>% group_by(Year, SpeciesCode) %>% summarise(count = sum(Band))

#now we want to reshape the dataframe so that we can determine what species have continuous data over the correct time period
sp.dat<-cast(sp.dat, SpeciesCode~Year, value="count")

write.csv(sp.dat, paste(out.dir, site, "BandSummary.csv", sep=""), row.names = FALSE, append = TRUE, quote = FALSE, sep = ",", col.names = TRUE)

} #end of site loop
```
